### ISSUE TITLE
ogg loader is panicking with my ogg files with index out of bounds error?

### ISSUE THREAD

**Issue by Hellzbellz123** [harudagondi/bevy_oddio#48]
tried setting oddio up in my project, originally i used ogg files for testing but the ogg loader included was crashing with below error
the panic from line 37 always prints twice, line 49 only prints once.  switched to wav and that loader is working as intended but the file is x10 the size so i would rather return to ogg.
```
thread 'IO Task Pool (0)' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/hellzbellz/.cargo/git/checkouts/bevy_oddio-ae6b627b20902565/6020986/src/loader/ogg_loader.rs:37:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'IO Task Pool (2)' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/hellzbellz/.cargo/git/checkouts/bevy_oddio-ae6b627b20902565/6020986/src/loader/ogg_loader.rs:37:54
thread 'IO Task Pool (1)' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/hellzbellz/.cargo/git/checkouts/bevy_oddio-ae6b627b20902565/6020986/src/loader/ogg_loader.rs:49:44
```

**Comment by harudagondi** [comment]
This is weird. This means that parsing your ogg audio file results in a list of frames that contain no samples. Also, if this is from using only one audio file, then this case is peculiar, as it somehow assumes that the ogg file is both mono and stereo simultaneously.

**Comment by Hellzbellz123** [comment]
i currently have bevy_audio disabled
https://github.com/Hellzbellz123/oddio_error_example is repro
i finally got around too creating a minimal reproduction of the error with the given asset files, the minimal reproduction throws this error too 
```
2022-10-07T02:58:50.933229Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070", vendor: 4318, device: 9352, device_type: DiscreteGpu, backend: Vulkan }
thread 'thread 'Async Compute Task Pool (2)Async Compute Task Pool (1)' panicked at '' panicked at 'Cannot build output stream.: StreamConfigNotSupportedCannot build output stream.: StreamConfigNotSupported', ', C:\Users\Hellzbellz\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_oddio-0.2.0\src\output.rsC:\Users\Hellzbellz\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_oddio-0.2.0\src\output.rs::9090::1010

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-10-07T02:58:51.892540Z  INFO oddio_error_example: spacebar pressed
thread 'IO Task Pool (2)' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\Hellzbellz\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_oddio-0.2.0\src\loader\ogg_loader.rs:37:54
```

**Comment by harudagondi** [comment]
For the first error it seems that you cannot build an output stream because it is not supported in your device. This is similar to #36. Have you tried running examples from [cpal]?

For the second problem, I tested your audio file, and it seems that the packets are not what I expected. I'm currently busy, so I couldn't fix the problem right now. In the mean time, if you are willing to contribute, you could try replacing `lewton` with `symphonia` and see how it works? Or try studying the `ogg` format to see how to fix it?

[cpal]: https://github.com/RustAudio/cpal
